name: Countries
version: '${project.version}'
main: dvdcraft.countries.Countries
api-version: 1.18
authors: [ dvdishka ]
description: Countries plugin
commands:
  country:
    description: "Main command of Countries plugin"